stages:
  - deploy

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

before_script:
  - echo "Checking out the repository..."
  - git checkout $CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  image: mcr.microsoft.com/appsvc/staticappsclient:stable
  script: 
    - echo "Deploying to Azure Static Web Apps..."
    - npx swa deploy ./ --api-location ./api --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN
  only:
    - main