stages:
  - validate
  - deploy

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

validate:
  stage: validate
  image: alpine:latest
  script:
    - echo "=== Validating deployment files ==="
    - pwd
    - echo "Repository structure:"
    - find . -type f -name "*.html" -o -name "*.css" -o -name "*.js" | head -20
    - echo "Public directory contents:"
    - ls -la public/
    - echo "CSS file verification:"
    - 'if [ -f "public/css/styles.css" ]; then echo "✓ styles.css found"; echo "File size: $(du -h public/css/styles.css)"; echo "Line count: $(wc -l < public/css/styles.css)"; head -5 public/css/styles.css; else echo "✗ styles.css NOT found"; exit 1; fi'
    - echo "HTML files verification:"
    - 'for file in public/*.html; do if [ -f "$file" ]; then echo "✓ Found: $file ($(wc -l < "$file") lines)"; fi; done'
  artifacts:
    paths:
      - public/
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: node:18-alpine
  dependencies:
    - validate
  before_script:
    - echo "=== Pre-deployment checks ==="
    - node --version
    - npm --version
    - ls -la public/
    - 'if [ -f "public/css/styles.css" ]; then echo "✓ CSS file present ($(wc -l < public/css/styles.css) lines)"; else echo "✗ CSS file missing!"; exit 1; fi'
  script: 
    - echo "Installing Azure Static Web Apps CLI..."
    - npm install -g @azure/static-web-apps-cli
    - echo "Deploying to Azure Static Web Apps..."
    - npx swa deploy ./public --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN --verbose
    - echo "Deployment completed"
  after_script:
    - echo "=== Deployment Summary ==="
    - echo "Pipeline ID:$CI_PIPELINE_ID"
    - echo "Commit SHA:$CI_COMMIT_SHA"
    - 'if [ -f "public/css/styles.css" ]; then echo "Final CSS verification: $(wc -l < public/css/styles.css) lines"; fi'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
