stages:
  - deploy

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

before_script:
  - echo "Checking out the repository..."
  - git checkout $CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  image: node:14
  script: 
    - echo "Installing Azure Static Web Apps CLI..."
    - npm install -g @azure/static-web-apps-cli
    - echo "Deploying to Azure Static Web Apps..."
    - npx swa deploy ./ --api-location ./api --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN
  only:
    - main