stages:
  - build
  - deploy

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

build:
  stage: build
  image: node:14
  script: 
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  image: mcr.microsoft.com/appsvc/staticappsclient:stable
  script: 
    - |
      echo "Deploying to Azure Static Web Apps..."
      curl -sL https://deb.nodesource.com/setup_14.x | bash -
      apt-get install -y nodejs
      npm install -g @azure/static-web-apps-cli
      npx swa deploy ./public --api-location ./api --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN
  only:
    - main