stages:
  - deploy

variables:
  AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

deploy:
  stage: deploy
  image: node:18
  script: 
    - echo "Installing Azure Static Web Apps CLI..."
    - sudo npm install -g @azure/static-web-apps-cli --unsafe-perm
    - echo "Deploying to Azure Static Web Apps..."
    - sudo npx swa deploy ./public --env production --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always